@echo off
echo Checking Node.js version...
node -v
echo.

echo Starting MongoDB...
start cmd /k "mongod"

echo Waiting for MongoDB to start...
timeout /t 5

echo Starting server...
cd server
echo Installing server dependencies...
call npm install
echo Starting server...
start cmd /k "npm start"

echo Waiting for server to start...
timeout /t 5

echo Starting client...
cd ../client
echo Installing client dependencies...
call npm install
echo Starting client...
start cmd /k "npm start"

echo Application is starting...
echo Server will be available at http://localhost:6001
echo Client will be available at http://localhost:3000 